#!/bin/sh

echo "cmake_minimum_required(VERSION 3.14)
project($1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(Boost  COMPONENTS  REQUIRED)
include_directories(\${BOOST_INCLUDE_DIRS})

add_executable($1
  main.cpp
)

target_link_libraries($1 \${Boost_LIBRARIES})
" > CMakeLists.txt
